{
 "title": "Apollo server overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "commands",
    "query": {
     "query": "label_values(apollo_command_response,command_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Golden metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(apollo_command_response{status=\"success\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(apollo_command_response{status=\"error\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Request rate by commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Command: $commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "repeat": "commands",
   "targets": [
    {
     "expr": "sum by(status) (rate(apollo_command_response{command_name=\"$commands\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Outgoing requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Audio provider response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "apollo_response_time{command_name=\"play\", quantile=\"0.99\"}",
     "legendFormat": "{{function_name}}"
    }
   ]
  },
  {
   "title": "Search results provider response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "apollo_response_time{command_name=\"search\", quantile=\"0.99\"}",
     "legendFormat": "{{function_name}}"
    }
   ]
  }
 ]
}