global:
  scrape_interval: 5s

scrape_configs:
  - job_name: apollo-server
    static_configs:
      - targets: ["apollo-server:3001"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]